version: '3.9'
services:
  db-mysql:
    image: "mysql:latest"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationski
      - MYSQL_PASSWORD=root
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      retries: 5

  station-ski:
    depends_on:
      db-mysql:
        condition: service_healthy
    image: wissalmechmeche/stationski:1.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db-mysql:3306/stationski?createDatabaseIfNotExist=true
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.MySQL5InnoDBDialect
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    stdin_open: true
    tty: true
  angular-app:
    image: wissalmechmeche/stationskifront:1.0
    ports:
      - "4200:4200"
    depends_on:
      - db-mysql
      - station-ski
    restart: unless-stopped

volumes:
  db:
