version: '3.9'

services:

  db-mysql:
    image: "mysql:latest"
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=stationSki
    ports:
      - "3306:3306"
    volumes:
      - db:/var/lib/mysql

  station-ski:
    depends_on:
      - db-mysql
    image: wissalmechmeche/stationski:1.0
    restart: on-failure
    ports:
      - "8089:8089"
    environment:
      SPRING_APPLICATION_JSON : '{
        "spring.datasource.url" : "jdbc:mysql://localhost:3306/stationSki?createDatabaseIfNotExist=true",
        "spring.datasource.username" : "root",
        "spring.datasource.password" : null,
        "spring.jpa.properties.hibernate.dialect" : "org.hibernate.dialect.MySQL5InnoDBDialect",
        "spring.jpa.hibernate.ddl-auto" : "update"
      }'
    stdin_open: true
    tty: true
volumes:
  db:

















